# Generated by Django 5.1.7 on 2025-05-04 17:05

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_passwordresettoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresettoken',
            options={},
        ),
        migrations.RenameField(
            model_name='passwordresettoken',
            old_name='token',
            new_name='otp',
        ),
        migrations.AlterUniqueTogether(
            name='passwordresettoken',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='email',
            field=models.EmailField(default='defaultEmail', max_length=254),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=users.models.get_default_expires_at),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='icon.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(error_messages={'unique': 'Email này đã được đăng ký'}, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(error_messages={'unique': 'Số điện thoại này đã tồn tại'}, max_length=15, unique=True),
        ),
    ]
