# Generated by Django 5.1.6 on 2025-03-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='Default.png', upload_to=''),
        ),
    ]
