# Generated by Django 5.1.6 on 2025-03-18 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrows', '0004_alter_borrow_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='borrow',
            table='Borrows',
        ),
    ]
