# Generated by Django 5.1.7 on 2025-05-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrows', '0005_alter_borrow_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='borrow_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='borrow_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='exp_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
