# Generated by Django 5.1.7 on 2025-05-18 17:23

import borrows.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrows', '0006_borrow_borrow_days_alter_borrow_borrow_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='require_date',
            field=models.DateTimeField(default=borrows.models.default_require_date),
        ),
    ]
