# Generated by Django 5.1.7 on 2025-05-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrows', '0007_borrow_require_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('BORROWED', 'BORROWED'), ('OVERDUE', 'OVERDUE'), ('RETURNED', 'RETURNED'), ('LOST', 'LOST'), ('CANCELED', 'CANCELED')], default='PENDING', max_length=255),
        ),
    ]
