# Generated by Django 5.1.6 on 2025-03-18 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notification',
            table='Notifications',
        ),
    ]
